baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "PRIME"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[markup.goldmark.renderer]
unsafe = true


[params]
# In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
google_analytics_id = ""
google_tag_manager_id = ""
favicon = "favicon-32x32.svg"

[params.homepage]
sticky_header = false
show_contact_box = false      # show / hide the contaxt box on the homepage
show_services_button = false # show / hide the "view all services" button
show_services = false
show_features = false

[params.logo]
mobile = "images/logo/logo-prime.png"
mobile_height = "52px"
desktop = "images/logo/logo-prime.png"
desktop_height = "52px"
alt = "Protecting Minority Ethnic Communities Online"

[params.fonts]
# sets the google font link in layouts/partials/google-fonts.html
google_fonts = 'https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Poppins:wght@200;400&display=swap'
heading = "Playfair Display"
base = "Source Sans Pro"

[params.colors]
primary = "#284973"
black = "#000000"
white = "#ffffff"
white_offset = "#f6f7ff"
grey = "#5C5A5A"

[params.seo]
meta_twitter_site = "@protectingME"
meta_twitter_creator = "@protectingME"
meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

[params.services]
summary_truncate = 120 # How many characters to include in the summary of the services before truncating

[params.team]
summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

[params.footer]
copyright_text = 'This work is supported by the Engineering and Physical Sciences Research Council grant number EP/W032333/1 . Â© 2025 PRIME Project'

[menu]
# Main Menu
[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.main]]
name = "Partners"
identifier = "partners"
url = "/partners/"
weight = 3

[[menu.main]]
parent = "partners"
name = "Advisory board"
url = "/partners/advisory-board/"
weight = 1

[[menu.main]]
parent = "partners"
name = "Community partners"
url = "/partners/community-partners"
weight = 2

[[menu.main]]
name = "News"
url = "/news/"
weight = 4

[[menu.main]]
name = "Outputs"
url = "/outputs/"
weight = 5

[[menu.main]]
parent = "Outputs"
name = "Graphics"
url = "/outputs/graphics"
weight = 1

[[menu.main]]
parent = "Outputs"
name = "Posters"
url = "/outputs/posters"
weight = 3

[[menu.main]]
parent = "Outputs"
name = "Links and media"
url = "/outputs/links-and-media"
weight = 4

[[menu.main]]
parent = "Outputs"
name = "Code of practice"
url = "/outputs/code-of-practice"
weight = 6

[[menu.main]]
parent = "Outputs"
name = "Policy briefs"
url = "/outputs/policy-briefs"
weight = 7

[[menu.main]]
parent = "Outputs"
name = "Videos"
url = "/outputs/videos"
weight = 8

[[menu.main]]
parent = "Outputs"
name = "Design guidelines"
url = "/outputs/desing-guidelines"
weight = 10

[[menu.main]]
parent = "Outputs"
name = "PRIME Technical Toolkit"
url = "https://primetoolkit.co.uk/"
weight = 7


[[menu.main]]
parent = "Outputs"
name = "Academic publications"
url = "/outputs/academic-publications"
weight = 5

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 6

# Footer Menu
[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2

[taxonomies]
tag = "tags"